export type colorVariants = "yellow"
    | "blue"
    | "red"
    | "indigo"
    | "gray"
    | "purple"
    | "pink"
    | "black"
    | "white"


export type colorVariantsNumbers = "50" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900"

export type fontSizeVariants = "sm"
    | "lg"
    | "xs"
    | "xl"
    | "base"
    | "2xl"
    | "3xl"
    | "4xl"
